### ISSUE TITLE
./build/bin/main is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by onlyone-hyphen** [SJTU-IPADS/PowerInfer#123]
**Windows 11**

Step 1) Clone the repo and CD into it
Step 2) Run the following commands
```
cmake -S . -B build -DLLAMA_CUBLAS=ON
cmake --build build --config Release
```
Step 3) Download Llama 7B PowerInfer GGUF
Step 4) Run the following 
`./build/bin/main -m ./llama-7b.gguf -n 128 -t 8 -p "Once upon a time"`

Result:
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/149725370/50ac298e-ee0a-4f3a-a71a-fa5afc841b25)

**Comment by hodlen** [comment]
It looks like you might be encountering a path syntax issue specific to Windows, as our README provides instructions using Unix-style paths. On Windows, you should use backslashes (\) instead of forward slashes (/). Try simply replacing `./build/bin/main` with `.\build\bin\main` in your command, as well as adjusting the model path accordingly.

Also, thank you for pointing this out! We will work on providing more clear instructions in our README.

**Comment by onlyone-hyphen** [comment]
Ah I feel silly now, there was another problem though too, main.exe is inside the Release folder so the correct path for Windows users is `build\bin\Release\main.exe` after opening a terminal in the `PowerInfer-main` folder
