### ISSUE TITLE
FFN Offloading Failed: Activation_32 Not Found (Very slow inference)

### ISSUE THREAD

**Issue by onlyone-hyphen** [SJTU-IPADS/PowerInfer#131]
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/149725370/a7033f4c-ea13-48a7-9a9b-59faac6c7995)

Inference is very slow (12 tokens per second), I get 35 tokens per second with LLM Studio, based on reading the PowerInfer paper I was expecting closer to 100/200 tokens per second on my hardware (i7-12700H, 64GB RAM, NVIDIA 4060 Laptop - Windows 11 Pro)

As you see in the screenshot, there is an uncaught exception because it's looking for a file (activation_32) that does not exist, activation_31 is the last file.

Due this it seems to be reverting to "slow mode"

I checked huggingface for the missing file, but it doesn't exist
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/149725370/90f8c12f-660a-415a-a4ee-ad8fcefc5cae)

To reproduce on Windows 11.

Download python 3.10 from the Microsoft Store
Download cmake from cmake.org
Clone PowerInfer repo
Follow instructions on PowerInfer readme (build using cmake and for NVIDIA GPU)
Choose the 7b llama 2 model, and place it in the models folder
Download the activation folder too and put it in the models folder
Run inference

Inference works, but FFN offloading fails due to uncaught exception (above)

**Comment by hodlen** [comment]
I am wondering if your `activations` directory containing files other than activation files named `*.pt`. If so, it can trigger a bug in the FFN split script and disable this feature, and further slowing down the generation speed.

**Comment by onlyone-hyphen** [comment]
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/149725370/2af2efed-71da-4440-a9ea-de909b1476f6)
![image](https://github.com/SJTU-IPADS/PowerInfer/assets/149725370/a803cc44-6fc5-4132-bd73-2a44928951fe)
This is what happens when you drink nothing but coffee for 48 hours straight

Thank you so much :)

**Comment by hodlen** [comment]
Hahaha but that's a kind reminder bro. The program should handle such cases. I'll reopen this and do an easy fix soon.

**Comment by hodlen** [comment]
Performance issue is quite complex and varies a lot on different hardware. But for your case, I think the major issue is due to PowerInfer introduces additional overhead on CPU-GPU sync when the model can fit in VRAM as a whole (7B INT4 model v.s. 8 GB VRAM). Please kindly refer to #128 for more explanation on this point. 

KV cache size can also affect performance when the context grows up, since you mentioned the generation speed dropped after ~500 tokens. The context size is 512 token by default, and you can try setting `-c` or `--ctx-size` to set a larger KV cache to fix this.

**Comment by onlyone-hyphen** [comment]
Ah I see, Thank you for the clarification
